services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: finance_app
    environment:
      - MONGO_URL=mongodb://mongo:27017/finance_demo
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: finance_mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: